# PyTorch 란?

PyTorch는 Python 기반의 과학 연산 패키지이다.
- GPU 및 다른 가속기의 성능을 사용하기 위한 NumPy의 대체제 제공
- 신경만 구현에 유용한 automatic differntiation 라이브러리 제공

# 튜토리얼의 목표

- 높은 수준에서 PyTorch의 Tensor library와 Neural Network의 이해
- Image classification neural net 학습

# Tensor

Tensor는 Array 또는 matrix와 매우 유사한 특수 자료구조이다. PyTorch에서는 tensor를 사용하여 모델의 입력과 출력 그리고 모델의 매개변수를 encode한다.

GPU나 다른 연산 가속을 위한 특수한 하드웨어에서 실행할 수 있다는 점을 제외 시, Tensor는 NumPy의 ndarray와 매우 유사하다.

In [1]:
import torch
import numpy as np

# Tensor 초기화하기

텐서는 여러가지 방법으로 초기화가 가능하다.

1. 데이터로부터 directly 생성하기  
   데이터로부터 직접 텐서를 생성이 가능하다.   
   data type은 자동으로 유추한다.

In [3]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

print(data)
print(x_data)

[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])


2. NumPy 배열로부터 생성하기  
   텐서는 NumPy 배열로 생성할 수 있다.

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


3. 다른 텐서로부터 생성하기  
    명시적으로 override하지 않는다면, 인자로 주어진 텐서의 속성(shape, datatype)을 유지한다.

In [5]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지한다.
print(f"Ones Tensor: \n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어쓴다.
print(f"Random Tensor: \n {x_rand}\n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])

Random Tensor: 
 tensor([[0.7104, 0.9394],
        [0.2967, 0.2804]])



4. Random or constant 값을 사용하기  
   shape은 텐서의 dimension을 나타내는 tuple로 아래 함수들에서는 출력 텐서의 차원을 결정한다.

In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9689, 0.3240, 0.7011],
        [0.4977, 0.7724, 0.1311]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Tensor Attribute (텐서의 속성)

텐서의 속성은 tensor의 shape, datatype 및 어느 장치에 저장되는지를 나타낸다.

In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
print(tensor)

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
tensor([[0.9179, 0.4670, 0.3133, 0.3104],
        [0.1536, 0.6952, 0.9906, 0.8419],
        [0.7496, 0.9065, 0.8263, 0.3611]])


# 텐서 연산 (Operation)

transposing, indexing, slicing, 수학계산, 선형 대수, random sampling 등 100가지 이상의 텐서 연산이 가능.

각 연산들은 GPU에서 실행이 가능하다.

In [10]:
# GPU가 존재하면 텐서를 이동
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")
else:
    print("cpu use")

cpu use


1. NumPy 식의 표준 인덱싱과 슬라이싱

In [27]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


2. torch.cat : 주어진 차원에 따라 일련의 텐서를 연결 가능. (4by4를 3개 붙이면 12by4로)
3. torch.stack : 한 차원을 늘려서 받음. (4by4를 3개 붙이면 4by4 3개로)

In [30]:
#dim = 0 : 아래로 붙이기 (행 늘리기)
#dim = 1 : 옆으로 붙이기 (열 늘리기)
t1 = torch.cat([tensor, tensor, tensor], dim = 0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [33]:
t2 = torch.stack([tensor, tensor, tensor], dim = 0)
print(t2)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


4. 텐서 곱하기

In [34]:
# 요소별 곱 (element-wise product)을 계산
print(f'tensor.mul(tensor)\n {tensor.mul(tensor)}\n')
# 다른 문법
print(f'tensor * tensor \n {tensor * tensor}')

tensor.mul(tensor)
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


5. 두 텐서 간의 행렬 곱(matrix multiplication)을 계산

In [35]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# 다른 문법:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


6. in-place 연산 : 접미사를 갖는 연산들은 in-place 연산.  
   ex) x.copy_(), x.t_()는 x를 변경한다.

In [36]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


in-place 연산은 메모리를 일부 절약하지만, 기록이 즉시 삭제되어 derivative 계산에 문제를 발생시킬 수 있음. 따라서, 사용을 권장하지 않음.

# NumPy 변환(Bridge)

cpu 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다.

1. tensor -> NumPy array

In [37]:
t = torch.ones(5)
print(f't: {t}')
n = t.numpy()
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


텐서의 변경 사항이 NumPy 배열에 반영된다.

In [39]:
t.add_(1)
print(f't: {t}')
print(f'n: {n}')


t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


2. NumPy -> Tensor

In [40]:
n = np.ones(5)
t = torch.from_numpy(n)

In [41]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
